spring.application.name=springproject

server.port = 8080
spring.datasource.url = jdbc:mysql://localhost:3306/maskpack
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto = create-drop
# 없는 테이블 생성 — 종료할 때 삭제하지 않음
# spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode = always
spring.jpa.defer-datasource-initialization = true
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=classpath:/sql/data_mask.sql

# 이번 실행에서 데이터 삽입 always , none
# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.encoding=UTF-8
# spring.sql.init.data-locations=classpath:/sql/data_mask.sql